[font]
size = 16

[font.normal]
#family = "JetBrainsMono Nerd Font Mono"
family = "Hack Nerd Font"
#family = "sketchybar-app-font"
[window]
decorations = "buttonless"
startup_mode = "Maximized"
padding = { x = 3, y = 3 }
dynamic_padding = true
#opacity = 0.9
